### ISSUE TITLE
problema con encoding nei nomi dei layers

### ISSUE THREAD

**Issue by micheleborella** [geosolutions-it/MapStore2-C028#10]
I nomi dei layers nella lista dei livelli non vengono visualizzati correttamente se contengono caratteri con accenti o umlaut (ä, ö...).

**Comment by offtherailz** [comment]
Questa problematica è già stata fixata sul repository principale di MapStore 2: https://github.com/geosolutions-it/MapStore2/issues/1435

Per sistemare il problema sarà neccessario allinearsi alla opportuna revision di MapStore 2 e aggiornare il seguente file: 
https://github.com/geosolutions-it/MapStore2-C028/blob/master/index.html#L5
con 
```
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
```

**Comment by offtherailz** [comment]
Ho applicato il fix e allinato MapStore2 alla opportuna revision e funziona. 
Le mappe che contengono layer con errori di encoding devono essere corrette e ri-salvate. Le modifiche sono già sul server di test e sul branch master di questo repo.  
Aspetto conferma per chiudere la issue.
