### ISSUE TITLE
ELK Stack installation

### ISSUE THREAD

**Issue by giacomoc92** [geosolutions-it/MapStore2-C028#100]
Destination machine: 10.160.90.90

Fill the document as the installation proceeds https://docs.google.com/document/d/1tCalGT2U0AlfUEwQzK76RkloAt5sNtHIPwH4MftU1mk/edit#

Components:
- [x] Logstash
- [x] Elasticsearch
- [x] Kibana
- [x] Filebeat (geoserver node)

**Comment by giacomoc92** [comment]
Moving this to blocked until Monday, when we can deploy filebeat.

**Comment by randomorder** [comment]
@giacomoc92 
Monitor plugin configuration [here](https://drive.google.com/open?id=1dl1t-dKcWh_JcO7lKmlooEgCOjPRcypB). **this is standard for all deployments**
Filebeat configuration example [here](https://drive.google.com/open?id=123EwHG2orCrkcMAeD-Wg0dAMXogBpwCV). **this requires adjustments** for the environment (for instance the `output.logstash` section)

**Comment by randomorder** [comment]
> Fill the document as the installation proceeds https://docs.google.com/document/d/1tCalGT2U0AlfUEwQzK76RkloAt5sNtHIPwH4MftU1mk/edit#

please put the doc in the project directory

**Comment by giacomoc92** [comment]
I have installed filebeat and the plugin on the test machine (geoserv02). moving on to the prod machines.

**Comment by giacomoc92** [comment]
Installation is complete. Moving on to the configuration
