### ISSUE TITLE
ELK stack configuration 

### ISSUE THREAD

**Issue by giacomoc92** [geosolutions-it/MapStore2-C028#101]
Destination machine: 10.160.90.90

Fill the document as the installation proceeds https://docs.google.com/document/d/1tCalGT2U0AlfUEwQzK76RkloAt5sNtHIPwH4MftU1mk/edit#

Configure the stack components, geoserver included. Data retention should be 2/3 weeks.

**Comment by giacomoc92** [comment]
ATM the stack is running and we can see the events sent from geoserver02. We can't see the events from geoserv01 and 03, it's probably a configuration error as filebeat and monitoring are deployed.

TODO: 

- [ ] Find out why kibana is not receiving events from geoserv01 and 03
- [ ] Setup visualizations and the dashboard in the UI

**Comment by tdipisa** [comment]
@giacomoc92 @randomorder 
geoserver02 is a test machine and we don't have to monitor that machine, why we should monitor this?

What we have to monitor is the GeoServer cluster, in particular the cluster nodes on geoserv03.

**Comment by giacomoc92** [comment]
Monitoring plugin was misconfigured, everything is working as intended now. I have fixed it and updated the docs accordingly.

Now i need to setup the kibana UI

**Comment by giacomoc92** [comment]
The setup for the visualizations, dashboard and searches is done.

**Comment by tdipisa** [comment]
@giacomoc92 @randomorder skype has problem now. Let's try to schedule a meeting this afternoon for a check. @giacomoc92 can you please include some links:

- Kibana instance
- Related deploy doc

**Comment by giacomoc92** [comment]
[Document](https://docs.google.com/document/d/1tCalGT2U0AlfUEwQzK76RkloAt5sNtHIPwH4MftU1mk/edit#)

The kibana instance is only accessible via their remote desktop at 84.18.123.20
