### ISSUE TITLE
Comune Bolzano - MapStore Test Deploy

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#113]
The MapStore instance in test should be updated with the latest improvements regarding style localizations and project update

**Comment by randomorder** [comment]
Can you pass @giacomoc92 the WAR file @tdipisa ?

**Comment by giacomoc92** [comment]
Is this operation already scheduled with the client?

**Comment by tdipisa** [comment]
@randomorder @giacomoc92  I will provide the war file soon. The activiy is not already scheduled with the client, My intention was only to first schedule it internally.

**Comment by giacomoc92** [comment]
I have deployed the new war. We are seeing some UI problems.
![remmina_Bolzano_84 18 128 20_2020519-135448,081201](https://user-images.githubusercontent.com/49372260/82336554-0a749c00-99eb-11ea-881f-f6c047e4e58f.png)
![Uploading remmina_Bolzano_84.18.128.20_2020519-135513,423277.png…]()

**Comment by randomorder** [comment]
please let us know @tdipisa

**Comment by tdipisa** [comment]
@randomorder @giacomoc92 this is only a cache issue, moving to test
