### ISSUE TITLE
GeoServer WEB-INF/lib directory differs between environments

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2-C028#114]
As reported by the client OJDBC driver in the Webapp on the Test Environment. Align with PROD and test

**Comment by giacomoc92** [comment]
removed the file from /geoserver/geoserver/lib, environments are now aligned.

**Comment by randomorder** [comment]
Doc updated? @giacomoc92

**Comment by giacomoc92** [comment]
Yes
