### ISSUE TITLE
ELK Training

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#115]
- Possible use cases and samples: how to use a dashboard to catch up with errors and identify performance issues
- Doc for instance and services management
- Others? TBD

**Comment by tdipisa** [comment]
@randomorder I think we can at least start scheduling this for July, not urgent.

**Comment by tdipisa** [comment]
Training scheduled for August 11 at 9:30am
The analysis report to use as a reference [here](https://docs.google.com/document/d/15DwYTdAY5iVYrKsz_sMYCc_BmfLNPaq4ZY7KEVKfOxE/edit?usp=sharing). The training agenda below:
![image](https://user-images.githubusercontent.com/1280027/89047180-5aa69d80-d34e-11ea-968c-18856d93cd20.png)

**Comment by randomorder** [comment]
this should be done
