### ISSUE TITLE
ComuneBZ - GeoServer Datadir Broken in Test (geoserv02)

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2-C028#116]
Client reported GeoServer not coming back online after restart. I found the datadir to be broken @tdipisa . Notably:
- Empty `logginx.xml` (not necessarily a show stopper)
- missing `default.xml` in the workspaces directory
- missing `workspace.xml` in each one of the workspaces!

I don't know how this may have happened and there may be other issues with the datadir. I restored a backup copy from the 30th of March found on the machine.

**Notes**:
- GeoServer is running now but Must be tested before handing it over to the client @giacomoc92 
- The OJDBC issue #114  still needs to be looked at (not that urgent though)

**Comment by randomorder** [comment]
I said already but let me emphasize it: I did not test GeoServer. Up to you @giacomoc92

**Comment by giacomoc92** [comment]
So far I have tried: 

- stop and start geoserver
- load an existing map from mapstore
- create a new map from mapstore

Everything seems to be working fine. is there anything else to test?

**Comment by randomorder** [comment]
Just test the layers are working, especially the ones from Oracle

**Comment by giacomoc92** [comment]
I have tested the Oracle layers and they are working
