### ISSUE TITLE
Configure Search services is not working

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#123]
If I click on [Configure Search Service button](https://mapstore.readthedocs.io/en/latest/user-guide/menu-bar/#configuring-a-search-service) nothing happens: configuration issue?
c028 project has a custom search services configured, if it is not possible to make the **Configure Search Service** properly runnung we can disable it.

**Comment by tdipisa** [comment]
@MV88 If possible disable the search by aeronautical coordinates.

**Comment by MV88** [comment]
> @MV88 If possible disable the search by aeronautical coordinates.

is not possible to remove the cog icon, because it is always shown if the coordinate search is visible
![image](https://user-images.githubusercontent.com/11991428/83004284-c3e8f800-a00f-11ea-873b-2a4d9fe6e7c8.png)

**Comment by MV88** [comment]
we will remove the burger menu and leave only address search bar
