### ISSUE TITLE
No API version in Share tool

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C028#127]
From the homepage the Share tool should not show the API in thr Emded tab.

*Current Result*
 ![current.JPG](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/71ae74a9-7430-443a-a95d-5b8c2f74d2cb)

*Expected Result*
![expected.JPG](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/c4e0c683-2f77-4313-921f-29157a72bf16)

**Comment by tdipisa** [comment]
@gitcontributor the problem reported in this issue has not been resolved yet: as you can see in [homepage of test instance](https://sit.comune.bolzano.it/mapstore3/#/) the share through API is still present.

**Comment by MV88** [comment]
a new deploy is needed
