### ISSUE TITLE
Review of the ELK Stack configuration

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#129]
Review dashboard config of what provided in #101

**Comment by randomorder** [comment]
Hi @giacomoc92 
A few questions:
- Firewall: have you set up anything on the machine? Is there an agreement with the client on whether it is required to set it up and who will take care of configuring it?
- Indexes rotation in Elasticsearch: Are you removing old indexed or it just keep ingesting events until it is either unusable or fills up the whole disk? Was there an agreement on the "retention period" of the events?

**Comment by randomorder** [comment]
Also I don't see and Cron job to remove audit files on the machines to prevent filling up the disks. Is there anything in place?

**Comment by giacomoc92** [comment]
> Firewall

My setup was done according to this [document](https://docs.google.com/document/d/1DnB1XUOI95L48vG8noNX6ntKj0bfZx8tMwxk9iRfjpU/edit#) which has no mention of any specific firewall configuration. So, I haven't touched it.

> Indexes rotation in Elasticsearch

It should be configured to have a ~3 weeks retention

**Comment by randomorder** [comment]
> > Firewall
> 
> My setup was done according to this [document](https://docs.google.com/document/d/1DnB1XUOI95L48vG8noNX6ntKj0bfZx8tMwxk9iRfjpU/edit#) which has no mention of any specific firewall configuration. So, I haven't touched it. The machine doesn't have internet access anyway.

I don't know what you're talking about. The document does not get into the details on the activities to perform on the machine in any way (and it shouldn't). You set up the machine, it is your duty to ask yourself the question "should I configure the firewall on this thing?" The answer in this case is probably no but you should raise the hand and ask if unsure.

> It should be configured to have a ~3 weeks retention

Where / how is it configured? Is it documented?

> As for the audits, the rotation should be set in logrotate

Audits are rotated automatically by GeoServer, I am asking about file removal. Are they files also removed by Logrotate?

**Comment by giacomoc92** [comment]
> Audits are rotated automatically by GeoServer, I am asking about file removal. Are they files also removed by Logrotate?

yes

> Where / how is it configured? Is it documented?

From kibana ui -> management -> index lifecycle policies. It is not in the document, should I update it?

**Comment by randomorder** [comment]
> > Audits are rotated automatically by GeoServer, I am asking about file removal. Are they files also removed by Logrotate?
> 
> yes

What the retention time?
(This is not documented either)

> > Where / how is it configured? Is it documented?
> 
> From kibana ui -> management -> index lifecycle policies. It is not in the document, should I update it?

Yes

**Comment by randomorder** [comment]
[From the tecnical proposal](https://docs.google.com/document/d/1DnB1XUOI95L48vG8noNX6ntKj0bfZx8tMwxk9iRfjpU/edit#bookmark=id.pwz7x9w41vb5):
```
...Si prevede di configurare un periodo di retention dei dati iniziale di 2-3 settimane massimo...
```
Current configuration:

![image](https://user-images.githubusercontent.com/5264230/85147136-b0b3fb80-b24e-11ea-93dd-ac7388cd488e.png)

90 + 28 and a size limit of 50 GB which seems way too high to me

**Comment by giacomoc92** [comment]
> > > Audits are rotated automatically by GeoServer, I am asking about file removal. Are they files also removed by Logrotate?
> > 
> > 
> > yes
> 
> What the retention time?
> (This is not documented either)

It should rotate weekly. Going to add this to the document of each machine.

> > > Where / how is it configured? Is it documented?
> > 
> > 
> > From kibana ui -> management -> index lifecycle policies. It is not in the document, should I update it?
> 
> Yes

I will update this too

**Comment by randomorder** [comment]
> It should rotate weekly. Going to add this to the document of each machine.

Does not seem to be the case:
```
-rw-r--r-- 1 tomcat tomcat 36565 Jun 22 10:30 geoserver_audit_20200622_62.log
-rw-r--r-- 1 tomcat tomcat 95124 Jun 22 01:50 geoserver_audit_20200621_61.log
-rw-r--r-- 1 tomcat tomcat 95123 Jun 21 01:50 geoserver_audit_20200620_60.log
...
-rw-r--r-- 1 tomcat tomcat  3396 May  3 01:50 geoserver_audit_20200502_2.log-20200510.xz
-rw-r--r-- 1 tomcat tomcat    32 May  3 00:00 geoserver_audit_20200430_0.log-20200510.xz
-rw-r--r-- 1 tomcat tomcat    32 May  3 00:00 geoserver_audit_20200501_1.log-20200510.xz
```

> I will update this too

Have you read [my comment above](https://github.com/geosolutions-it/MapStore2-C028/issues/129#issuecomment-646687192)?

**Comment by giacomoc92** [comment]
> > It should rotate weekly. Going to add this to the document of each machine.
> 
> Does not seem to be the case:
> 
> ```
> -rw-r--r-- 1 tomcat tomcat 36565 Jun 22 10:30 geoserver_audit_20200622_62.log
> -rw-r--r-- 1 tomcat tomcat 95124 Jun 22 01:50 geoserver_audit_20200621_61.log
> -rw-r--r-- 1 tomcat tomcat 95123 Jun 21 01:50 geoserver_audit_20200620_60.log
> ...
> -rw-r--r-- 1 tomcat tomcat  3396 May  3 01:50 geoserver_audit_20200502_2.log-20200510.xz
> -rw-r--r-- 1 tomcat tomcat    32 May  3 00:00 geoserver_audit_20200430_0.log-20200510.xz
> -rw-r--r-- 1 tomcat tomcat    32 May  3 00:00 geoserver_audit_20200501_1.log-20200510.xz
> ```

This will need to be checked up

> > I will update this too
> 
> Have you read [my comment above](https://github.com/geosolutions-it/MapStore2-C028/issues/129#issuecomment-646687192)?

> 90 + 28 and a size limit of 50 GB which seems way too high to me

Then we can lower the delete phase to 28 and hot phase to a couple of days? Do we need a lower a size limit?

**Comment by randomorder** [comment]
> This will need to be checked up

Ok, please open an issue to track this

> Then we can lower the delete phase to 28 and hot phase to a couple of days? Do we need a lower a size limit?

I suggest you check the documentation and understand how[ the phases](https://www.elastic.co/guide/en/kibana/master/creating-index-lifecycle-policies.html) work and if / how it makes sense to use them this scenario

**Comment by randomorder** [comment]
Also take the occation to close #146

**Comment by giacomoc92** [comment]
> > This will need to be checked up
> 
> Ok, please open an issue to track this
> 
> > Then we can lower the delete phase to 28 and hot phase to a couple of days? Do we need a lower a size limit?
> 
> I suggest you check the documentation and understand how[ the phases](https://www.elastic.co/guide/en/kibana/master/creating-index-lifecycle-policies.html) work and if / how it makes sense to use them this scenario

I have checked the documentation and I don't think it makes sense to mess with those settings.
The logs seem to end up all inside the container. I will need to research this

**Comment by randomorder** [comment]
nevermind @giacomoc92 
I'll revire the rotation myself

**Comment by randomorder** [comment]
Documented [here](https://docs.google.com/document/d/1tCalGT2U0AlfUEwQzK76RkloAt5sNtHIPwH4MftU1mk/edit#heading=h.46mpksyb9xa3)
