### ISSUE TITLE
New Deploy of MS in Test

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#136]
A new deploy is needed in test env for latest updates.

**Comment by MV88** [comment]
@giacomoc92 [here](http://demo.geo-solutions.it/share/comunebz/) is the mapstore.war for deploy in test

**Comment by giacomoc92** [comment]
The new was is deployed but I am unable to login

**Comment by tdipisa** [comment]
@giacomoc92 did you use the user **tdipisa**? In that case, is the ldap.properties properly filled @MV88 @giacomoc92?

**Comment by giacomoc92** [comment]
editing geostore-spring-security.xml seems to have worked.

changed `<property name="userDn" value="combzmapstore"/>
` to `<property name="userDn" value="combz\mapstore"/>
`

**Comment by giacomoc92** [comment]
Also, might be unrelated, but the map `geosolutions_test_19_05_2020` is using "/geoserver2/wms" for the catalog, making mapstore look for a geoserver at `geoserv02:8083/geoserver2/` which does not exists.
![remmina_Bolzano_84 18 128 20_202063-16427,225225](https://user-images.githubusercontent.com/49372260/83660393-13f22c80-a5c5-11ea-84da-ccff3adddfa1.png)

**Comment by tdipisa** [comment]
@MV88 @giacomoc92 I've checked the deploy and it seems that the ldap.properties file is missing in the deployed war: it should be located at /mapstore2/WEB-INF/classes right?

**Comment by MV88** [comment]
the output directory of the pom is /src/main/webapp/WEB-INF/classes

**Comment by MV88** [comment]
To check if the credentials have been applied correctly is enough to check the geostore-spring-security.xml 

The transfer from ldap.properties to geostore-spring-security.xml is made during build process
The ldap.properties configuration must not be versioned

**Comment by giacomoc92** [comment]
This is what the mapstore deploy document says regarding ldap.properties

> Configuration files: 
webapps/mapstore2/WEB-INF/classes/spring-security.xml (copied from ldap.properties at build time)

https://docs.google.com/document/d/1I1ZvH47mUrgZVKs-kuneal8Kqi29vXyrkYqKvtuX9ZE/edit#
