### ISSUE TITLE
Cleanup file system on the machines

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2-C028#146]
There is lots of garbage around the file system. Take the time and cleanup what is not required

For instance, on the test machine at `/geoserver`:
```
backup
backup30032020
data
data_10072018
data_10_07_2018.tar.gz
data.bak
geonetwork
geoserver
geoserver_old
GWC_DATA_DIR
gwclogs
images
log_tomcat
lost+found
mapstore2
mapstore2.war
ortofoto
shape
shape.bkp
shape_for_test
shape_puc
static
tomcat-test
upload
```

**Comment by randomorder** [comment]
@giacomoc92 
Since you're checking the ELK documentation / setup  please do this as well

**Comment by giacomoc92** [comment]
I have removed some of the garbage/old backups.

there is a 'data_previous' directory'. what is it? do we need it?
drwxr-xr-x 26 tomcat   tomcat  4096 Jun  4 15:07 data_previous

**Comment by randomorder** [comment]
A backup of the data directory prior to our recent work to align Test with Prod. Please move it to the backup directory

**Comment by randomorder** [comment]
are we done @giacomoc92 ?

**Comment by giacomoc92** [comment]
yes, i'm closing this
