### ISSUE TITLE
New Deploy of MS in Test

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C028#150]
A new deploy is needed in test env for latest updates.

@giacomoc92 [here](http://demo.geo-solutions.it/share/comunebz/) is the mapstore.war for deploy in test

**Comment by giacomoc92** [comment]
I have deployed the new war, everything seems fine.

**Comment by tdipisa** [comment]
@giacomoc92, let's check the new deploy. I will get back to you if needed.
