### ISSUE TITLE
WPS Call for gs:Bounds fails

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#151]
The request is failing

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/097bc2b6-3bb6-43ca-a2c2-04392a2c9ad7)

**Request URL**
https://sit.comune.bolzano.it/geoserver2/wps?service=WPS&ms2-authkey=d3995d3d-1dae-45e5-865b-627280a51961

**Request Body**
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute service="WPS"   version="1.0.0"
    xmlns="http://www.opengis.net/wps/1.0.0"
    xmlns:gml="http://www.opengis.net/gml"
    xmlns:ogc="http://www.opengis.net/ogc"
    xmlns:ows="http://www.opengis.net/ows/1.1"
    xmlns:wcs="http://www.opengis.net/wcs/1.1.1"
    xmlns:wfs="http://www.opengis.net/wfs"
    xmlns:wps="http://www.opengis.net/wps/1.0.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"   xsi:schemaLocation="http://www.opengis.net/wps/1.0.0  http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
    <ows:Identifier>gs:Bounds</ows:Identifier>
    <wps:DataInputs>
        <wps:Input>
            <ows:Identifier>features</ows:Identifier>
            <wps:Reference method="POST" mimeType="text/xml" xlink:href="http://geoserver/wfs">
                <wps:Body>
                    <wfs:GetFeature service="WFS" version="1.1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><wfs:Query typeName="Ambiente:quartieri" srsName="EPSG:4326"></wfs:Query></wfs:GetFeature>
                </wps:Body>
            </wps:Reference>
        </wps:Input>
    </wps:DataInputs>
    <wps:ResponseForm>
        <wps:RawDataOutput mimeType="application/json">
            <ows:Identifier>bounds</ows:Identifier>
        </wps:RawDataOutput>
    </wps:ResponseForm>
</wps:Execute>

**Comment by offtherailz** [comment]
It is really slow.

```
 time curl 'http://geoserv02:8080/geoserver/wps?service=WPS'   -H 'Connection: keep-alive'   -H 'Pragma: no-cache'   -H 'Cache-Control: no-cache'   -H 'Authorization: Basic Ym9semFubzpib2x6YW5v'   -H 'Accept: application/json, text/plain, */*'   -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'   -H 'Content-Type: text/xml'   -H 'Origin: http://geoserv02:8080'   -H 'Referer: http://geoserv02:8080/mapstore2/'   -H 'Accept-Language: it,de;q=0.9,it-IT;q=0.8,en-US;q=0.7,en;q=0.6'   -H 'Cookie: GS_FLOW_CONTROL="GS_CFLOW_-58547e70:1722c116720:-7f98"'   --data-binary $'<?xml version="1.0" encoding="UTF-8"?>\n<wps:Execute service="WPS"   version="1.0.0"\n    xmlns="http://www.opengis.net/wps/1.0.0"\n    xmlns:gml="http://www.opengis.net/gml"\n    xmlns:ogc="http://www.opengis.net/ogc"\n    xmlns:ows="http://www.opengis.net/ows/1.1"\n    xmlns:wcs="http://www.opengis.net/wcs/1.1.1"\n    xmlns:wfs="http://www.opengis.net/wfs"\n    xmlns:wps="http://www.opengis.net/wps/1.0.0"\n    xmlns:xlink="http://www.w3.org/1999/xlink"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"   xsi:schemaLocation="http://www.opengis.net/wps/1.0.0  http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">\n    <ows:Identifier>gs:Bounds</ows:Identifier>\n    <wps:DataInputs>\n        <wps:Input>\n            <ows:Identifier>features</ows:Identifier>\n            <wps:Reference method="POST" mimeType="text/xml" xlink:href="http://geoserver/wfs">\n                <wps:Body>\n                    <wfs:GetFeature service="WFS" version="1.1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><wfs:Query typeName="Ambiente:quartieri" srsName="EPSG:4326"></wfs:Query></wfs:GetFeature>\n                </wps:Body>\n            </wps:Reference>\n        </wps:Input>\n    </wps:DataInputs>\n    <wps:ResponseForm>\n        <wps:RawDataOutput mimeType="application/json">\n            <ows:Identifier>bounds</ows:Identifier>\n        </wps:RawDataOutput>\n    </wps:ResponseForm>\n</wps:Execute>'   --compressed   --insecure --write-out time_total
<?xml version="1.0" encoding="UTF-8"?><ows:BoundingBox xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1"><ows:LowerCorner>11.276342879215713 46.444728424038914</ows:LowerCorner><ows:UpperCorner>11.43285577614062 46.530401610788985</ows:UpperCorner></ows:BoundingBox>time_total
real    4m22.144s
user    0m0.016s
sys     0m0.000s
```
**4m22s**. The real process is slow, but this (probably due to oracle??) is very very slow

**Comment by offtherailz** [comment]
https://github.com/geosolutions-it/MapStore2/pull/5433
