### ISSUE TITLE
Deploy in Production

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#160]
The activities are the following:

- [ ] Update deploy for MS
- [x] Migration of the GeoServer data dir from Test to PROD and review of the needed configs

The above points need #132, then:

- [ ] Dismiss the old version of MS (temporary backup of the webapp and the DB is required)
- [ ] Testing

**Comment by randomorder** [comment]
Scheduled for July the 8th

**Comment by randomorder** [comment]
See checlist at #132
