### ISSUE TITLE
GeoServer Update to 2.18.2 in Test

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#181]
We have to update the GeoServer instance to the latest stable.

- [x] GeoServer update from current version 2.16.2 to the latest stable 2.18.2 in test environment
- [ ] ~~Alignment with production DATA_DIR (optional)~~
- [x] Upgrade to JDK 11 with Marlin Renderer included
- [x] After the update check also the ticket [here](https://github.com/geosolutions-it/support/issues/1247) and try to reproduce it to see if the issue is solved
- [ ] Enable the control flow (see notes below)
- [x] Test of the update
- [ ] Documentation update

**GeoServer extensions installed**
The updated list of extensions installed should be [this one](https://docs.google.com/document/d/1zLx6AVpjP8frJUtSU6mmD9BD16hU9TKH9rT95VAmu14/edit#heading=h.ykxjwhjceco0). **Please review it** during the update and align same lists also in other deploy docs (eg. [here](https://docs.google.com/document/d/1UyYwTBlnbAqGz6zQaTpQ7bCLeRAvYQRhLFJs9irX628/edit#heading=h.ykxjwhjceco0) the list seems not updated)

- [x] The client recently asked to also install the [CSS extension](https://sourceforge.net/projects/geoserver/files/GeoServer/2.18.2/extensions/geoserver-2.18.2-css-plugin.zip/download) see issue #185

**About Control Flow**
Since we did not identify any particular critical issues during the last review of the infrastructure, as a first step we can enable it, obviously taking as a reference the system resources currently available but without setting a too stringent configuration. 
Once enabled in this way, the performance of the system should be kept under control also using Kibana to promptly intervene with further tuning if and where necessary.

**Comment by randomorder** [comment]
Would Thursday be ok @tdipisa ?

**Comment by tdipisa** [comment]
@randomorder yes for me, I will notify the client by mail.

**Comment by tdipisa** [comment]
@randomorder the update in Test environment is scheduled for next Tuesday, April 23.

**Comment by randomorder** [comment]
Geoserver war ready. I took the list of plugins from [here](https://docs.google.com/document/d/1zLx6AVpjP8frJUtSU6mmD9BD16hU9TKH9rT95VAmu14/edit#bookmark=id.f24kr94zyezh)

**Comment by lpasquali** [comment]
the issues exposed in freshdesk https://geosolutions.freshdesk.com/a/tickets/46713 look like to not persist anymore in test after geoserver upgrade @tdipisa @randomorder 
![Screenshot from 2021-05-25 13-23-35](https://user-images.githubusercontent.com/1780406/119489879-74412780-bd5c-11eb-9e5f-ea732dbd76ed.png)
