### ISSUE TITLE
GeoServer Update to 2.18.2 in Production

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#182]
We have to update the GeoServer instance to the latest stable as we did previously in Test environment (see #181):

- [x] GeoServer update from current version 2.16.2 to the latest stable 2.18.2 in test environment
- [x] Upgrade to JDK 11 with Marlin Renderer included
- [x] Enable the control flow as in test environment
- [ ] Test of the update
- [x] Documentation update

The updated list of extensions installed should be [this one](https://docs.google.com/document/d/1zLx6AVpjP8frJUtSU6mmD9BD16hU9TKH9rT95VAmu14/edit#heading=h.ykxjwhjceco0). **Please review it** during the update and align same lists also in other deploy docs (eg. [here](https://docs.google.com/document/d/1UyYwTBlnbAqGz6zQaTpQ7bCLeRAvYQRhLFJs9irX628/edit#heading=h.ykxjwhjceco0) the list seems not updated)

**Comment by randomorder** [comment]
waiting for the green light to move on here @tdipisa

**Comment by tdipisa** [comment]
@randomorder @lpasquali we can schedule for tomorrow, I've just sent an email to the client.

**Comment by randomorder** [comment]
good to go @lpasquali

**Comment by lpasquali** [comment]
@randomorder I see that tomcat upgrade is not listed in the activity task list above, but test is running tomcat8 while prod tomcat7

**Comment by randomorder** [comment]
it was not planned in DEV but required for the new GS version to work

please do the same for prod. Take a backup

**Comment by lpasquali** [comment]
- geoserv01 is upgraded, as well as instances on geoserv03
- there is a problem after upgrade for which geoserver is refusing let anyone connect from the  balancer, I think JAVA_OPTS is correct:
```
Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -server -Xms4096m -Xmx4096m -Duser.timezone=GMT -XX:+UseParallelGC -XX:SoftRefLRUPolicyMSPerMB=36000 -DGEOSERVER_DATA_DIR=$GEOSERVER_DATA_DIR -DGEOWEBCACHE_CACHE_DIR=$GEOWEBCACHE_CACHE_DIR -DGEOSERVER_AUDIT_PATH=/opt/logs/geoserver-audits -DGEOSERVER_LOG_LOCATION=/opt/logs/$INSTANCE_NAME.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/data/memory_dumps_dumpsa -DPROXY_BASE_URL=https://sit.comune.bolzano.it/geoserver -DGEOSERVER_CSRF_WHITELIST=sit.comune.bolzano.it"
```

**Comment by lpasquali** [comment]
geoserv03 has been upgraded (both instances)
I updated watchdogs for systemd and new services' paths
mapStore looks like is authenticating correctly to the new geoserver instances

**Comment by lpasquali** [comment]
Updated documentation
