### ISSUE TITLE
Blocking Irish and other site requests

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#183]
Check on Kibana to check requests received by the GeoServer from Ireland in order to identify the IPs and block them. 
Analyze the report on Kibana to see if there are also other IPs to block in general. The IPs must be communicated to Ing Marco Rizzardi who will subsequently block the IPs.

**Comment by lpasquali** [comment]
@tdipisa @randomorder 

I made two new views:
- [ip addresses for country](http://kibana:5601/app/kibana#/visualize/edit/ddd80130-d438-11eb-bfff-81a02f624ae3)
- [ip addresses for country (Irleand only)](http://kibana:5601/app/kibana#/visualize/edit/0bfdf830-d439-11eb-bfff-81a02f624ae3)

**Comment by randomorder** [comment]
ok, and?
is this done? should we communicate it to the client? do you still need to identify the ip addresses? ....

**Comment by lpasquali** [comment]
> ok, and?
> is this done? should we communicate it to the client? do you still need to identify the ip addresses? ....

no I have two views that do that for me :)
Irish ones:
```
52.114.77.26
52.114.77.236
46.137.73.20
34.243.19.150
185.4.193.230
176.34.215.18
104.41.225.52
```

**Comment by lpasquali** [comment]
@randomorder as I said their concern is quite understandable, within available history of ES such 7 ip addresses, specially two, did a quarter million of requests

**Comment by randomorder** [comment]
yes please

**Comment by lpasquali** [comment]
> yes please

@randomorder I'd add links to documentation rather than integrate them with the dashboard as they are something to use after one has evidence in the map of huge traffic (bigger dot) on the map

**Comment by lpasquali** [comment]
docs updated

https://docs.google.com/document/d/1tCalGT2U0AlfUEwQzK76RkloAt5sNtHIPwH4MftU1mk/edit?ts=60c89540#bookmark=id.9c6xzoasqfj3

**Comment by lpasquali** [comment]
@randomorder @tdipisa as you see by mail, information dispached to customer
