### ISSUE TITLE
Comune di Bolzano GeoServer Update

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#186]
## Description
The Comune di Bolzano GeoServer need to be updated to the last stable version (eg. 2.22.2). It is a big jump since the current version is a 2.18.1.

**Involved steps:**

- [x] Prepare for the Test instance update (needed backups)
- [x] Update the Test GeoServer and first test using the GS admin UI
- [x] Extensive test through MS using the defined [test scenarios](https://studio.cucumber.io/projects/376223/test-plan/folders/2804759) recently migrated to Cucumber
- [x] If all test above are passed prepare for the Production instance update (needed backups)
- [x] Update the Production cluster (1 master and 2 slaves)
- [x] Extensive test through MS using the defined [test scenarios](https://studio.cucumber.io/projects/376223/test-plan/folders/2804759) recently migrated to Cucumber

**Comment by tdipisa** [comment]
@ElenaGallo test run to be executed: https://studio.cucumber.io/projects/376223/test-runs/777894/overview

**Comment by tdipisa** [comment]
@ElenaGallo the test GeoServer has been successfully updated to 2.22.2. You can start testing at your convenience. Below a summary of useful links:

- The test run to be executed: https://studio.cucumber.io/projects/376223/test-runs/777894/overview
- The test MapStore instance: https://sit.comune.bolzano.it/mapstore3/#/
- The internal document: https://docs.google.com/document/d/1YIsouC96wS7V1KhccAm4ZgnBOS4TJlJpQDpVIdiZuBI/edit#heading=h.yaisbb4ka31k

In addition to the usual test run we need to spend some time for a wide testing of OGC services by using MS.

**Comment by ElenaGallo** [comment]
@tdipisa I did the cucumber test run and all the tests pass: https://studio.cucumber.io/projects/376223/test-runs/777894/overview

**Comment by tdipisa** [comment]
@ElenaGallo also the production GeoServer has been successfully updated to 2.22.2. Deployment document also updated:

- GS master: https://docs.google.com/document/d/1dWA2fG2nlg3vszhNQZRolmX2_8ROqE_36x4jFyai1gM/edit#
- GS slaves: https://docs.google.com/document/d/1py7MwHt6gW1gzLGnzV0HsIX1RWuhCv4gi8XUJVC14wo/edit#

You can start testing at your convenience. Below a summary of useful links:

The test run to be executed: https://studio.cucumber.io/projects/376223/test-runs/780721/overview
The production MapStore instance: https://sit.comune.bolzano.it/mapstore2/#/
The internal document where you can find needed references and info for accessing the apps: https://docs.google.com/document/d/1YIsouC96wS7V1KhccAm4ZgnBOS4TJlJpQDpVIdiZuBI/edit#heading=h.yaisbb4ka31k

In addition to the usual test run we need to spend some time for a wide testing of OGC services by using MS.

**Comment by tdipisa** [comment]
I'm going to check tomorrow.
