### ISSUE TITLE
Dati mancanti in Feature Grid

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#34]
Nella mappa Aree Modificate non compare nessun dato all'interno della feature grid, messagio:

nessun dato disponibile 

Le richieste inviate per ottenere features ottengono un errore 500: user not found
l'analisi degli URL mostra che sono presenti due auth key differenti

**Comment by tdipisa** [comment]
Il problema dobrebbe essere già stato risolto su MS2 master

**Comment by offtherailz** [comment]
E' necessario rimuovere le ms2-autkey duplicate dalle mappe manualmente, come in questo caso:
https://github.com/geosolutions-it/MapStore2-C040/issues/129

**Comment by tdipisa** [comment]
Solved within the production deploy
