### ISSUE TITLE
No Data areas in mosaic 2016

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#36]
Vedi immagine sottostante:

![mosaico](https://user-images.githubusercontent.com/1280027/36847390-69eea4c0-1d5e-11e8-8915-1c9ab9700a68.png)

URL richiesta:

http://geoserv02:8080/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&LAYERS=Cartografia%3Amosaico_2016&STYLES=&SRS=EPSG%3A900913&CRS=EPSG%3A900913&TILED=true&ms2-authkey=5217de7d-bca6-4ece-a152-05f467281c3a&WIDTH=256&HEIGHT=256&BBOX=1252344.271424327%2C5860579.832681034%2C1262128.2110448296%2C5870363.772301536

**Comment by tdipisa** [comment]
Da una prima indagine fatta con @dromagnoli  embra che il problema sia nel dato. Si richiede ulteriore investigazione più approfondita con la geotiff a disposizione.

**Comment by tdipisa** [comment]
@micheleborella, can you please describe what you did to fix the problem?

**Comment by micheleborella** [comment]
Ho ricreato le overviews dall'immagine originale e impostato un transparent color.
