### ISSUE TITLE
GeoServer Upgrade PROD

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#63]
Upgrade the Gs version in PROD too using the one installed in TEST

Blocked by #61 
Blocked by #64
Requires #67

Note: 
- [x] MapStore2 must be upgrated contextually
- [x] Every static config file should set to point to MS2 print plugin config. This because custom mapfish print do not work with geoserver - https://github.com/geosolutions-it/MapStore2-C028/issues/64 (also for MS1 configurations)

**Comment by randomorder** [comment]
GeoServer updated in PROD

**Comment by offtherailz** [comment]
- MapStore2 updated 
 - old MS1 configurations aligned with current print service (tested)
-  Tests passed
