### ISSUE TITLE
GeoServer Update to 2.16.2 - Test Environment

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#90]
As part of the activities described in #89, the GeoServer update is also included. 
This activity need to be considered not only for maintenance purposes but also to support some of the **localization features** described in #89 (tag sld: Localize): the current GeoServer version installed is not supporting the LANGUAGE parameter for GetLegendGraphic requests.

The current version of GeoServer used by the Municipality of Bolzano is **2.13.1** and also the most recent MapStore's [Timeline plugin](https://mapstore.readthedocs.io/en/latest/user-guide/timeline/) is not supported by this version. 

Within this issue an update of GeoServer will be provided to version **2.16.2**. Below is the list of plugins to be kept in the update:

- authkey-plugin
- charts-plugin
- control-flow-plugin
- oracle-plugin
- wps-download-plugin
- wps-plugin
- dxf-plugin

Below is the list of new plugins to include in the update:

- WMTS multidimensional (needed for the MS Timeline tool)
- CSS plugin (optional for the Style Editor plugin)

After the deploy review and update the [deployment diagram](https://docs.google.com/drawings/d/1FcR37mxi3-hw0pzSlq_3q3mR7_aLEe7yDB-g9TjEu2k/edit) if needed by producing an updated document **SIT ComuneBZ - 2020**

**Comment by randomorder** [comment]
@giacomoc92 I agreed with @tdipisa you'll perform the update early next week, probably on monday. Please make sure that by COB on friday you have a clear unerstanding of the task to perform, remote access to the infrastructure and prepared the GeoServer war file to be deployed, ok?
