### ISSUE TITLE
Elastic Stack Deployment

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#97]
A Stack Elastic must be provided as part of the Client's SDI infrastructure to monitor GeoServer (the accepted tech proposal for this work is available [here](https://docs.google.com/document/d/1DnB1XUOI95L48vG8noNX6ntKj0bfZx8tMwxk9iRfjpU/edit)).

A dedicated VM will be provided by the client for this installation. The following resources have been required:
- RAM: 32 GB
- CPU: 4 core 
- Disk: suggested SSD, at least 100Gb required  (the client cannot provide an SSD)
- SO: OpenSUSE latest version

Below are the required activities for this work (separated issues will be created as needed for this epic):

- Deploy of the required VM (the client will take care of this) 
- Elastic Stack installation
- Configuration e tuning
- Monitoring period (3-4 weeks) 
- Results check and analysis related to the monitoring period (with a final tech report)
- Training (how to use Kibana and also how to interpret the kibana's dashboard and monitoring results)

**Comment by randomorder** [comment]
we'll be waiting for the VM to be ready

**Comment by tdipisa** [comment]
@randomorder 

The new server is ready.

Nome: kibana
Indirizzo IP: 10.160.90.90
CPU: 4
RAM: 32GB
S.O.: openSUSE 13.1
Software: docker, docker-compose, systemd
Disco: 100GB liberi su /kibana

We can proceed with the Elastic Stack installation as soon as possible according to our scheduling.
