### ISSUE TITLE
Querylayer GS plugin is missing in the current installation

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#99]
It is missing on both TEST and PROD environments.
Please install it in test before and then in production (first master then slave 1 and 2, please restart one instance at time)

**Comment by Gnafu** [comment]
@tdipisa querylayer plugin is installed in test: you can proceed with the validation.

**Comment by tdipisa** [comment]
@Gnafu it is working in Mapstore test too
please proceed with the installation in production tomorrow if you can, let me know.
